services:
  - type: web
    name: tigerhacks25-api
    runtime: python
    buildCommand: pip install uv && uv sync --active
    startCommand: uv run --active uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DATABASE_URL
        sync: false
